name: TimePlayed
main: me.bloodmc.timeplayed.TimePlayedPlugin
load: STARTUP
version: 0.2
api-version: 1.13
commands:
   played:
      description: Shows total time played since login.
      permission: me.bloodmc.timeplayed
      usage: /played